### PR TITLE
Unit Tests for Dinkly Flash 

### PR DESCRIPTION
**Pull request by Elliott250**
Unit tests for classes/core/base/BaseDinklyFlash.php. While writing the tests I found that the exists(key) function only returned true when the key did exist, but nothing otherwise. I also found that the getAll() didn't return anything. I made appropriate adjustments for both cases.

### CODE REVIEW

**Comment by lewsid** [comment]
Hi Elliott, thanks for doing this work. The only issue I see is with your proposed change to the pathing of the unit-tests. It's a minor thing, but they are intended to be run from the app root, as documented in the readme, like so:

`php tools/run_unit_tests.php`

This is for consistency - everything under the tools folder is intended to be called this way. If you could revert your commit for that one file, I'd be happy to merge your other work here. Thanks!

**Comment by Elliott250** [comment]
Ok that makes sense, I went ahead and reverted that commit. I also just updated the valid_config with the default configuration in config.yml. This was the only unit test that was failing "out of the box".

**Comment by Elliott250** [comment]
I finished up some formatting this morning. Let me know if there are any other issues you have.

**Comment by lewsid** [comment]
Cool, great work!

**Pull request merged**
